stages:
  - prepare
  - build
  - test
  - security
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  ECS_CLUSTER: my-ecs-cluster
  ECS_SERVICE: juice-shop-service
  ECS_TASK_DEFINITION: juice-shop-task-def
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

prepare:
  stage: prepare
  image: python:3.10
  script:
    - echo " Installing Python dependencies..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m nltk.downloader punkt stopwords
  artifacts:
    paths:
      - .venv/

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Juice Shop Docker image..."
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  only:
    - main

test:
  stage: test
  image: python:3.10
  script:
    - echo " Running unit tests..."
    - pytest tests/ || echo "No tests found"

security:
  stage: security
  image: python:3.10
  script:
    - echo "Running Juice Shop security automation..."

    # Log Analysis - Monitoring
    - python scripts/log_analysis.py > reports/log_analysis.txt

    # NLP Log Analysis - Intelligence
    - python scripts/nlp_logs.py > reports/nlp_logs.txt

    # Login Anomalies - Detection
    - python scripts/login_anomaly.py > reports/login_anomalies.txt

    # IP Lookup - Threat Intelligence
    - python scripts/ip_lookup.py > reports/ip_lookup.txt

    # Network Sniffing - Monitoring
    - python scripts/sniff_traffic.py > reports/sniff_traffic.txt

    # Web Scraper - Recon / SAST
    - python scripts/web_scraper.py > reports/web_scraper.txt

    # Encryption Testing - Compliance Check
    - python scripts/encryption_test.py > reports/encryption_test.txt

    # YARA Scanning - Malware Detection
    - python scripts/yara_scan.py > reports/yara_scan.txt
  artifacts:
    paths:
      - reports/
    expire_in: 1 week

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - echo " Deploying to AWS ECS..."
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
  only:
    - main