name: Juice Shop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyara-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords
      
      - name: Build Juice Shop 
        run: docker pull bkimminich/juice-shop

      - name: Run Juice Shop container
        run: |
            docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
            sleep 30
            docker ps | grep juice-shop
      
      - name: Run tests
        run: pytest tests/ || echo "No tests found"
      
      - name: Create reports directory
        run: mkdir -p reports
      
      - name: Run security scripts
        run: |
          python scripts/yarascan.py > reports/yarascan.txt || true
          python scripts/nlplog.py > reports/nlplog.txt || true
          python scripts/log_anomaly.py --file logs/logins.csv > reports/log_anomaly.html || true
          python scripts/log_analysis.py > reports/log_analysis.txt || true
          python scripts/ip_lookup.py > reports/ip_lookup.txt || true
          python scripts/web_scraper.py > reports/web_scraper.txt || true
          python scripts/crypto.py > reports/crypto.txt || true
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/