name: Juice Shop CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords
      
      - name: Build Docker image
        run: docker build -f app/Dockerfile -t my-juice-shop:latest ./app
      
      - name: Run Juice Shop
        run: |
          docker run -d --name juice-shop -p 3000:3000 my-juice-shop:latest
          sleep 15
      
      - name: Run tests
        run: pytest tests/ || echo "No tests found"
      
      - name: Create reports directory
        run: mkdir -p reports
      
      - name: Run security scripts
        run: |
          python scripts/test1.py
          python scripts/test2.py
          python scripts/nlp_logs.py > reports/nlp_logs.txt || true
          python scripts/login_anomaly.py > reports/login_anomalies.txt || true
          python scripts/ip_lookup.py > reports/ip_lookup.txt || true
          python scripts/web_scraper.py > reports/web_scraper.txt || true
          python scripts/encryption_test.py > reports/encryption_test.txt || true
          python scripts/yara_scan.py > reports/yara_scan.txt || true
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/