name: Juice Shop CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt stopwords

      - name: Save .venv folder (cache)
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

  build:
    runs-on: ubuntu-latest
    needs: prepare
    services:
      docker:
        image: docker:20.10.24
        options: --privileged
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3

      - name: Build Juice Shop Docker image
        run: docker build -t my-juice-shop:latest ./app

      - name: Run Juice Shop container
        run: |
          docker run -d --name juice-shop -p 3000:3000 my-juice-shop:latest
          sleep 15
          echo "Juice Shop is running in Docker!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/ || echo "No tests found"

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install Python on Node base
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run security scripts
        run: |
          echo "Running security scripts..."
          python3 scripts/test1.py
          # Uncomment below lines when ready:
          # python3 scripts/nlp_logs.py > reports/nlp_logs.txt
          # python3 scripts/login_anomaly.py > reports/login_anomalies.txt
          # python3 scripts/ip_lookup.py > reports/ip_lookup.txt
          # python3 scripts/sniff_traffic.py > reports/sniff_traffic.txt
          # python3 scripts/web_scraper.py > reports/web_scraper.txt
          # python3 scripts/encryption_test.py > reports/encryption_test.txt
          # python3 scripts/yara_scan.py > reports/yara_scan.txt

      - name: Upload reports artifact
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: reports/
